# -*- coding: utf-8 -*-
"""financeTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/rcoborod/colab/blob/master/financeTest.ipynb
"""

import os
import pathlib
import datetime
import IPython
import IPython.display
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf

mpl.rcParams['figure.figsize'] = (8, 6)
mpl.rcParams['axes.grid'] = False

np.set_printoptions(precision=4)

!pip install yfinance
import yfinance as yf

data = yf.download("^GSPC",interval='1d',auto_adjust=True)

df= data.drop(columns=['Volume']).apply(np.log2)

date_time=pd.to_datetime(df.index,infer_datetime_format=True)
date_time

date_time.size
a=np.arange(0,date_time.size*4,4)
b=np.random.randint(1,3,size=(date_time.size))
c = 3 - b
b += a
c += a
d = a +3
a,b,c,d

df['Open']
#pd.Series(df['Open'],index=a)
df['io']=a
df['ih']=b
df['il']=c
df['ic']=d
df[['io','Open']].values
kk=pd.DataFrame(data=df['Open'].values,index=df['io'].values,  columns=['val'] )
kk=kk.append(pd.DataFrame(data=df['High'].values,index=df['ih'].values,  columns=['val'] ),sort=True)
kk=kk.append(pd.DataFrame(data=df['Low'].values,index=df['il'].values, columns=['val'] ),sort=True)
kk=kk.append(pd.DataFrame(data=df['Close'].values,index=df['ic'].values, columns=['val'] ),sort=True)

df
kk

kk.sort_index(inplace=True)
(kk*0).sort_index()
kk